version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:55"
    timezone: America/Phoenix
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: handlebars
    versions:
    - 4.7.6
